services:
    video-downloader:
        container_name: ${PROJECT_NAME}-video-downloader
        env_file:
            - .env.local
        build:
            dockerfile: ./Dockerfile
            args:
                SERVICE_PORT: 5000
                SERVICE_NAME: video-downloader
        restart: unless-stopped
        networks:
            - api_network
        volumes:
            - ./:/app
        command: celery -A src.main.celery worker --loglevel=info --queues=video_downloader
        ports:
            - "5000:5000"

networks:
  api_network:
    name: api_network
    driver: bridge
