# Production environment override
services:
  video-downloader:
      build:
          dockerfile: ./Dockerfile
          target: prod
          args:
              SERVICE_PORT: 5000
              SERVICE_NAME: video-downloader
